# These global settings will override any command line option passed to the
# tool when invoking the `batch` command.
delay:      30s
dry-run:    True
repository: docker/docker

# A list of operations to run as part of the batch job.
operations:

    # Functionally equivalent to running:
    #
    #   $> poule prune --action=ping \
    #                  --threshold=3m --grace-period=2w \
    #                  --filter ~label=kind/enhancement,kind/feature
    #
    - type: prune
      settings: {
          action:             ping,
          filters: {
              ~labels:        [ kind/enhancement, kind/feature ]
          },
          grace-period:       2w,
          outdated-threshold: 3m
      }

    # Functionally equivalent to running:
    #
    #   $> poule rebuild experimental win2lin
    #
    - type: rebuild
      settings: {
          configurations: [
              experimental,
              win2lin
          ]
      }
