# These global settings will override any command line option passed to the
# tool when invoking the `batch` command.
delay:      30s
dry-run:    True
repository: docker/docker

# A list of operations to run as part of the batch job.
operations:

    # Functionally equivalent to running:
    #
    #   $> poule --filter is:issue label label \
    #            --match aufs:"area/storage/aufs"
    #            --match devicemapper:"area/storage/devicemapper"
    #            --match overlay:"area/storage/overlay"
    #
    - type: label
      filters: {
          ~labels:            [ kind/enhancement, kind/feature ]
      }
      settings: {
          matches: {
              "aufs":         "area/storage/aufs",
              "devicemapper": "area/storage/devicemapper",
              "overlay":      "area/storage/overlay"
          }
      }

    # Functionally equivalent to running:
    #
    #   $> poule --filter ~label=kind/enhancement,kind/feature prune\
    #            --threshold=3m --grace-period=2w
    #
    - type: prune
      filters: {
          ~labels:            [ kind/enhancement, kind/feature ]
      }
      settings: {
          action:             ping,
          grace-period:       2w,
          outdated-threshold: 3m
      }

    # Functionally equivalent to running:
    #
    #   $> poule rebuild experimental win2lin
    #
    - type: rebuild
      settings: {
          configurations: [
              experimental,
              win2lin
          ]
      }
