# These global settings will override any command line option passed to the
# tool when invoking the `batch` command.
delay:      30s
dry-run:    True
repository: docker/docker

# A list of operations to run as part of the batch job.
operations:

    # Functionally equivalent to running:
    #
    #   $> poule --filter is:issue label label \
    #            --pattern "area/storage/aufs:aufs"
    #            --pattern "area/storage/devicemapper:devicemapper:
    #            --pattern "area/storage/overlay:overlay"
    #
    - type: label
      filters: {
          ~labels: [ kind/enhancement, kind/feature ]
      }
      settings: {
          patterns: {
              area/storage/aufs:         [ "aufs" ]
              area/storage/devicemapper: [ "devicemapper" ]
              area/storage/overlay:      [ "overlay" ]
          }
      }

    # Functionally equivalent to running:
    #
    #   $> poule --filter ~label=kind/enhancement,kind/feature prune\
    #            --threshold=3m --grace-period=2w
    #
    - type: prune
      filters: {
          ~labels: [ kind/enhancement, kind/feature ]
      }
      settings: {
          action:             ping,
          grace-period:       2w,
          outdated-threshold: 3m
      }

    # Functionally equivalent to running:
    #
    #   $> poule rebuild experimental win2lin
    #
    - type: rebuild
      settings: {
          configurations: [
              experimental,
              win2lin
          ]
      }
